### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by Pull2MAX** [ZAX130/ModeTv2#1]
Thank you for your work. In Figure 10 of your paper, I have been puzzled by what 'epoch=0' means. You also mentioned in section 4.5.3, 'Secondly, in cross-domain PO experiments across different brain MRI datasets (M2L and L2M), our model achieved relatively high DSC values even without PO (epoch=0).' Does 'epoch=0' mean that the default initialization weights of modelTV2 are used? Could you please tell me the meaning of 'epoch=0'? Thank you

**Comment by ZAX130** [comment]
This indicates that no PO was conducted, and the model trained directly with source domain data was utilized for inference on the target domain dataset.
