### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by marinaa05** [ZAX130/ModeTv2#3]
After I successfully run the train.py file and move onto infer.py, I get error:
`[Errno 2] No such file or directory: 'experiments/ModeTv2_cuda_nh(84211)_hd_6_ncc_1_reg_1_lr_0.0001_54r/`

In train.py, you wrote:
`save_dir = 'ModeTv2_cuda_nh({}{}{}{}{})_hd_{}_c_{}_ncc_{}_reg_{}_lr_{}_54r/'`

But in inder.py you request:
`model_folder = 'ModeTv2_cuda_nh({}{}{}{}{})_hd_{}_ncc_{}_reg_{}_lr_{}_54r/`

The two paths differ. Is this a mistake?

**Comment by ZAX130** [comment]
Apologies for the oversight. It can be fixed by unifying the two paths.

**Comment by ZAX130** [comment]
Thank you for pointing out the mistake.
